#!/usr/bin/sh

sxhkd &
# picom --backend glx --vsync &
xsetroot -cursor_name left_ptr &

# feh --bg-fill /home/master/.config/bspwm/wallpapers/bspwm-default-wallpaper.png
feh --bg-fill /home/master/.config/bspwm/wallpapers/lainwalledited.jpg
bspc monitor VGA-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d support

bspc config border_width 1
bspc config top_padding 0
bspc config bottom_padding 0
bspc config window_gap 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# setting node border colors
# bspc config normal_border_color "#462f4a"
bspc config normal_border_color "#5b2e63"
bspc config focused_border_color "#E97CFC"
# bspc config focused_border_color "#800099"

pkill -x polybar
polybar topbar -r

