#!/usr/bin/sh

# main configs
xset s off
xset s noblank
xset -dpms
sxhkd &
xsetroot -cursor_name arrow &
bspc monitor VGA-1 -d 1 2 3 4
bspc monitor HDMI-1 -d 1 2 3 4

# border configuring
bspc config border_width 3
bspc config top_padding 0
bspc config bottom_padding 0
bspc config window_gap 25
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# color configuring
bspc config normal_border_color "#19586d"
bspc config focused_border_color "#21c8ff"

pkill -x polybar
polybar bottombar1 -r 
