#!/usr/bin/sh

# disabling screensaver
xset s off
xset s noblank
xset -dpms
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 &

sxhkd &
bspc monitor VGA-1 -d 1 2 3 4
bspc monitor HDMI-1 -d 1 2 3 4

# border configuring
bspc config border_width 2
bspc config top_padding 0
bspc config bottom_padding 0
bspc config window_gap 15
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color "#19586d"
bspc config focused_border_color "#21c8ff"

xrdb -merge ~/.Xresources

pkill -x polybar
polybar bottombar1 -r 
