#!/usr/bin/sh

# disabling screensaver
xset s off
xset s noblank
xset -dpms

feh --bg-fill $HOME/vault/wallpapers/whitestuff.jpg # defining wallpaper

xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 & # defining cursor file

sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
# picom --config ~/.config/picom/picom.conf &
lxpolkit &
xbanish &
xdotool mousemove 1 1 &

# defining workspaces for each monitor
# bspc monitor VGA-1 -d • • • •
# bspc monitor HDMI-1 -d • • • •
bspc monitor VGA-1 -d 1 2 3 4 
bspc monitor HDMI-1 -d 4 3 2 1

# nodes config
# for side in top right bottom left; do bspc config ${side}_monocle_padding -15; done # fixing the padding for the screen sizes
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# node padding options
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

# setting focused border color
# bspc config focused_border_color "#FFFFFF"
# bspc config normal_border_color "#6e6b6b"
bspc config focused_border_color "#15adb0"

# defining certain apps to launch as floating
bspc rule -a pavucontrol state=floating
bspc rule -a Galculator state=floating
bspc rule -a Picture-in-Picture state=floating

# merging or "sourcing" the .Xresources configs
xrdb -merge ~/.Xresources

# killing and relaunching polybar's bars
pkill -x polybar 
polybar mainbar -r &
polybar secondbar -r &

# applying custom wacom board configurations
source ~/wacom_settings.sh
